### ISSUE TITLE
php use statements

### ISSUE THREAD

**Issue by designermonkey** [pedro151/starumlPHP#15]
I've structured a Model to have nested Packages. In one Package is a set of interfaces, and in it's child Package is a class that implements one of those interfaces.

The issue is that the class output has no knowledge of the parent level's namespace, so it just directly implements the interface name without a namespace preceding it, or having a use statement.

Being new to this code, I can't figure out how to create use statements for the class.

**Comment by ooga** [comment]
I'm currently testing an update to support use statements. I will submit the PR soon.

I hope this will solve your issue

**Comment by designermonkey** [comment]
Thanks very much!

**Comment by pedro151** [comment]
Thank you all for contributing
