### ISSUE TITLE
Generate Enums

### ISSUE THREAD

**Issue by mdarabi** [pedro151/starumlPHP#25]
Hi,

I figured out the enum generation does not work at all. To fix the problem I did two minor changes:
1. line 797: literlas -> literals
2. line 803: Comment it out

And now it works. I did not know any better way to let you know about it. Please remove this ticket later.

**Comment by ooga** [comment]
Hi,

You can submit your fix to review with a pull request
https://help.github.com/articles/creating-a-pull-request/
