### ISSUE TITLE
Code-files are not generated

### ISSUE THREAD

**Issue by ghost** [pedro151/starumlPHP#28]
Hi there,
I don't know exactly where the problem is, but when I try to generate my code, the folder named like the package is created, but there are no code-files in this folder. I never received any error-message.

**Comment by Konafets** [comment]
The DevTools shows this error:

<img width="726" alt="screen shot 2017-05-13 at 12 22 39" src="https://cloud.githubusercontent.com/assets/363363/26024694/f911e0ae-37d6-11e7-9bcd-c33c291e8668.png">

**Comment by Konafets** [comment]
Ok, the problem is that the current master is not tagged as latest release. Therefore StarUML pulls the latest release into its extension folder which contains the typo in the mentioned line above.

For a quick fix open the Extension Manager in StarUML, push the Button `Install from URL` and add this url `https://github.com/pedro151/starumlPHP/archive/master.zip`.

**Comment by ghost** [comment]
I tried it but it didn't helped: I get no warnings or messages in DevTools, but the folder named with the package name still keeps empty.
Any ideas?

**Comment by Konafets** [comment]
Go to `/Users/$USER/Library/Application\ Support/StarUML/extensions/user` and delete the folder `staruml.php`, than import the extension from the URL.

**Comment by ghost** [comment]
I tried now a few other programming languages and I think it's an issue by StarUML itself, because the behaviour is the same and there isn't any code file generated.
I created a new project for testing and there the code-generation works for PHP. The point is don't know exactly what the problem with my project is, I imagine it could be that I created multiple models and have inside these models class diagrams (if you make a right-click on a package, there you can add these).

**Comment by ghost** [comment]
Yeah, it works now! Obviously the error was by myself, because I moved the classes in the model-explorer inside the class-diagrams.

The only problem I have now is the left sidebar containing working diagrams: The class-diagrams are listed and after a "–" the parent folder is displayed. I have now 4 of these class-diagrams in this sidebar and one of them lists its parent folder as the package name, the rest displays the name of the parent model instead of their parent package name. Do you know how to adjust this?

Removing and readding the class-diagrams to working diagrams did it!
